// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmWYPDSfwtdSJ1s7CWT9fEVt46aJzaV_Q',
    appId: '1:891969447422:web:2927db9465c7c790cc8caf',
    messagingSenderId: '891969447422',
    projectId: 'meatz-b7635',
    authDomain: 'meatz-b7635.firebaseapp.com',
    storageBucket: 'meatz-b7635.appspot.com',
    measurementId: 'G-Z0JLP5H70T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEhCsE-Pso1mJCiDDX8bE-Hfvn-LlvJ8c',
    appId: '1:891969447422:android:62e90b6c4cb8acd6cc8caf',
    messagingSenderId: '891969447422',
    projectId: 'meatz-b7635',
    storageBucket: 'meatz-b7635.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWbzyQPWDwgWPSA5TVBsgu6QasCjfTemc',
    appId: '1:891969447422:ios:8a54fe1bec553208cc8caf',
    messagingSenderId: '891969447422',
    projectId: 'meatz-b7635',
    storageBucket: 'meatz-b7635.appspot.com',
    iosBundleId: 'com.example.meatz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWbzyQPWDwgWPSA5TVBsgu6QasCjfTemc',
    appId: '1:891969447422:ios:8a54fe1bec553208cc8caf',
    messagingSenderId: '891969447422',
    projectId: 'meatz-b7635',
    storageBucket: 'meatz-b7635.appspot.com',
    iosBundleId: 'com.example.meatz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmWYPDSfwtdSJ1s7CWT9fEVt46aJzaV_Q',
    appId: '1:891969447422:web:593a189bdf8e60f7cc8caf',
    messagingSenderId: '891969447422',
    projectId: 'meatz-b7635',
    authDomain: 'meatz-b7635.firebaseapp.com',
    storageBucket: 'meatz-b7635.appspot.com',
    measurementId: 'G-D61PN7TZVC',
  );
}
